### ISSUE TITLE
update the region input to follow the same pattern: `rds_region`

### ISSUE THREAD

**Issue by aaronlippold** [Staggerlee011/rds-bp-benchmark#4]

**Comment by Staggerlee011** [comment]
I had it as `region` instead of `rds_region` as im planning on writing a few profiles and wanted to remove duplicates of global vars. 

Hopefully be adding more soon! Ill leave this open incase I dont get them out, in which case i should update this one. 

S

**Comment by aaronlippold** [comment]
perhaps `aws_region` is more fitting then?
