### ISSUE TITLE
Remove Terraform tag control

### ISSUE THREAD

**Issue by bwmann** [Staggerlee011/rds-bp-benchmark#8]
Our team is not making use of Terraform, but instead using CloudFormation. Therefore, the following security control in configuration.rb requiring a Terraform tag should not be required:

```
control 'tags' do
  impact 0.5
  tag nist: ['CM-6']
  tag severity: 'medium'
  title 'has terraform created tags'
  describe aws_rds_instance(input('rds_name')) do
    its('tags') { should include('Terraform' => 'true') }
  end
end
```

Is it possible to maintain a separate branch where this security control is not included so that all security controls pass?

Thank you,
Braz

**Comment by bwmann** [comment]
Hello,

Just wanted to follow up on this issue. Can we have a second branch to maintain this alternate version without the Terraform tag?

Thanks,
Braz

**Comment by bwmann** [comment]
Following up - is it possible to grant myself access to be able to upload to a separate branch?

**Comment by aaronlippold** [comment]
I think we are going to refactor the core controls so you can just make a clean overlay on your side

**Comment by bwmann** [comment]
Yes, this has been set started - https://github.com/bwmann/idrs-rds-bp-benchmark-overlay

Closing
